apiVersion: v1
kind: Service
metadata:
  namespace: rockscripts381
  name: postgres  
  labels:
    app: odoo
spec:
  ports:
    - port: 5432
  selector:
    app: odoo
    tier: backend
  type: NodePort
